// ============================================================
// Role & Permission Constants
// ============================================================

export const ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  SUPERVISOR: 'supervisor',
  CASHIER: 'cajero',
  SELLER: 'vendedor',
  CLIENT: 'cliente',
  WAREHOUSE: 'almacen',
  ACCOUNTANT: 'contador',
};

export const ROLE_HIERARCHY = {
  super_admin: 100,
  admin: 80,
  supervisor: 70,
  accountant: 60,
  warehouse: 50,
  seller: 40,
  cajero: 30,
  cliente: 10,
};

export const PERMISSIONS = {
  // Sales
  SALE_CREATE: 'sale:create',
  SALE_READ: 'sale:read',
  SALE_UPDATE: 'sale:update',
  SALE_DELETE: 'sale:delete',
  SALE_CANCEL: 'sale:cancel',
  
  // Purchases
  PURCHASE_CREATE: 'purchase:create',
  PURCHASE_READ: 'purchase:read',
  PURCHASE_UPDATE: 'purchase:update',
  PURCHASE_APPROVE: 'purchase:approve',
  PURCHASE_RECEIVE: 'purchase:receive',
  
  // Products
  PRODUCT_CREATE: 'product:create',
  PRODUCT_READ: 'product:read',
  PRODUCT_UPDATE: 'product:update',
  PRODUCT_DELETE: 'product:delete',
  
  // Inventory
  INVENTORY_READ: 'inventory:read',
  INVENTORY_ADJUST: 'inventory:adjust',
  INVENTORY_TRANSFER: 'inventory:transfer',
  INVENTORY_COUNT: 'inventory:count',
  
  // Users
  USER_CREATE: 'user:create',
  USER_READ: 'user:read',
  USER_UPDATE: 'user:update',
  USER_DELETE: 'user:delete',
  
  // Clients
  CLIENT_CREATE: 'client:create',
  CLIENT_READ: 'client:read',
  CLIENT_UPDATE: 'client:update',
  
  // Suppliers
  SUPPLIER_CREATE: 'supplier:create',
  SUPPLIER_READ: 'supplier:read',
  SUPPLIER_UPDATE: 'supplier:update',
  
  // Invoices
  INVOICE_CREATE: 'invoice:create',
  INVOICE_READ: 'invoice:read',
  INVOICE_CANCEL: 'invoice:cancel',
  INVOICE_NCF: 'invoice:ncf',
  
  // Reports
  REPORT_READ: 'report:read',
  REPORT_EXPORT: 'report:export',
  
  // Ecommerce
  ECOMMERCE_MANAGE: 'ecommerce:manage',
  ECOMMERCE_READ: 'ecommerce:read',
  
  // Config
  CONFIG_READ: 'config:read',
  CONFIG_MANAGE: 'config:manage',
  
  // Accounting
  ACCOUNTING_CREATE: 'accounting:create',
  ACCOUNTING_READ: 'accounting:read',
  ACCOUNTING_POST: 'accounting:post',
  
  // Audit
  AUDIT_READ: 'audit:read',
  AUDIT_EXPORT: 'audit:export',
  
  // Notifications
  NOTIFICATION_READ: 'notification:read',
  NOTIFICATION_SEND: 'notification:send',
};

/**
 * Default role permission sets
 */
export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  
  [ROLES.ADMIN]: [
    PERMISSIONS.SALE_CREATE, PERMISSIONS.SALE_READ, PERMISSIONS.SALE_UPDATE, PERMISSIONS.SALE_CANCEL,
    PERMISSIONS.PURCHASE_CREATE, PERMISSIONS.PURCHASE_READ, PERMISSIONS.PURCHASE_UPDATE, PERMISSIONS.PURCHASE_APPROVE, PERMISSIONS.PURCHASE_RECEIVE,
    PERMISSIONS.PRODUCT_CREATE, PERMISSIONS.PRODUCT_READ, PERMISSIONS.PRODUCT_UPDATE, PERMISSIONS.PRODUCT_DELETE,
    PERMISSIONS.INVENTORY_READ, PERMISSIONS.INVENTORY_ADJUST, PERMISSIONS.INVENTORY_TRANSFER, PERMISSIONS.INVENTORY_COUNT,
    PERMISSIONS.USER_READ, PERMISSIONS.USER_CREATE, PERMISSIONS.USER_UPDATE,
    PERMISSIONS.CLIENT_READ, PERMISSIONS.CLIENT_CREATE, PERMISSIONS.CLIENT_UPDATE,
    PERMISSIONS.SUPPLIER_READ, PERMISSIONS.SUPPLIER_CREATE, PERMISSIONS.SUPPLIER_UPDATE,
    PERMISSIONS.INVOICE_CREATE, PERMISSIONS.INVOICE_READ, PERMISSIONS.INVOICE_CANCEL, PERMISSIONS.INVOICE_NCF,
    PERMISSIONS.REPORT_READ, PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.ECOMMERCE_MANAGE, PERMISSIONS.ECOMMERCE_READ,
    PERMISSIONS.CONFIG_READ, PERMISSIONS.CONFIG_MANAGE,
    PERMISSIONS.ACCOUNTING_READ,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.NOTIFICATION_READ,
  ],
  
  [ROLES.CASHIER]: [
    PERMISSIONS.SALE_CREATE, PERMISSIONS.SALE_READ,
    PERMISSIONS.PRODUCT_READ, PERMISSIONS.CLIENT_READ,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVOICE_CREATE, PERMISSIONS.INVOICE_READ,
    PERMISSIONS.NOTIFICATION_READ,
  ],
  
  [ROLES.SELLER]: [
    PERMISSIONS.SALE_CREATE, PERMISSIONS.SALE_READ,
    PERMISSIONS.PRODUCT_READ, PERMISSIONS.CLIENT_READ, PERMISSIONS.CLIENT_CREATE, PERMISSIONS.CLIENT_UPDATE,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.NOTIFICATION_READ,
  ],
  
  [ROLES.WAREHOUSE]: [
    PERMISSIONS.PRODUCT_READ, PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.INVENTORY_READ, PERMISSIONS.INVENTORY_ADJUST, PERMISSIONS.INVENTORY_TRANSFER, PERMISSIONS.INVENTORY_COUNT,
    PERMISSIONS.PURCHASE_READ, PERMISSIONS.PURCHASE_RECEIVE,
    PERMISSIONS.SALE_READ,
    PERMISSIONS.NOTIFICATION_READ,
  ],
  
  [ROLES.ACCOUNTANT]: [
    PERMISSIONS.SALE_READ, PERMISSIONS.PURCHASE_READ,
    PERMISSIONS.INVOICE_READ, PERMISSIONS.INVOICE_CANCEL, PERMISSIONS.INVOICE_NCF,
    PERMISSIONS.REPORT_READ, PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.ACCOUNTING_CREATE, PERMISSIONS.ACCOUNTING_READ, PERMISSIONS.ACCOUNTING_POST,
    PERMISSIONS.AUDIT_READ, PERMISSIONS.AUDIT_EXPORT,
    PERMISSIONS.CONFIG_READ,
  ],
  
  [ROLES.CLIENT]: [
    PERMISSIONS.ECOMMERCE_READ,
    PERMISSIONS.SALE_READ,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.CLIENT_READ, PERMISSIONS.CLIENT_UPDATE,
    PERMISSIONS.NOTIFICATION_READ,
  ],
};

export default { ROLES, ROLE_HIERARCHY, PERMISSIONS, ROLE_PERMISSIONS };
