/**
 * Definiciones de roles y permisos del sistema
 */

const ROLES = {
  ADMIN: 'admin',
  SUPERVISOR: 'supervisor',
  CASHIER: 'cajero',
  INVENTORY: 'inventario',
  CLIENT: 'cliente'
};

const PERMISSIONS = {
  // Usuarios
  USER_CREATE: 'user:create',
  USER_READ: 'user:read',
  USER_UPDATE: 'user:update',
  USER_DELETE: 'user:delete',
  USER_MANAGE_ROLES: 'user:manage_roles',

  // Productos
  PRODUCT_CREATE: 'product:create',
  PRODUCT_READ: 'product:read',
  PRODUCT_UPDATE: 'product:update',
  PRODUCT_DELETE: 'product:delete',

  // Categorías
  CATEGORY_CREATE: 'category:create',
  CATEGORY_READ: 'category:read',
  CATEGORY_UPDATE: 'category:update',
  CATEGORY_DELETE: 'category:delete',

  // Inventario
  INVENTORY_READ: 'inventory:read',
  INVENTORY_CREATE: 'inventory:create',
  INVENTORY_UPDATE: 'inventory:update',
  INVENTORY_ADJUST: 'inventory:adjust',
  INVENTORY_TRANSFER: 'inventory:transfer',

  // Compras
  PURCHASE_CREATE: 'purchase:create',
  PURCHASE_READ: 'purchase:read',
  PURCHASE_UPDATE: 'purchase:update',
  PURCHASE_CANCEL: 'purchase:cancel',

  // Ventas
  SALE_CREATE: 'sale:create',
  SALE_READ: 'sale:read',
  SALE_UPDATE: 'sale:update',
  SALE_CANCEL: 'sale:cancel',

  // Facturación
  INVOICE_CREATE: 'invoice:create',
  INVOICE_READ: 'invoice:read',
  INVOICE_UPDATE: 'invoice:update',
  INVOICE_SEND: 'invoice:send',

  // Reportes
  REPORT_READ: 'report:read',
  REPORT_EXPORT: 'report:export',

  // Clientes
  CLIENT_CREATE: 'client:create',
  CLIENT_READ: 'client:read',
  CLIENT_UPDATE: 'client:update',

  // Configuración
  CONFIG_READ: 'config:read',
  CONFIG_UPDATE: 'config:update',

  // Auditoría
  AUDIT_READ: 'audit:read',

  // Ecommerce
  ECOMMERCE_MANAGE: 'ecommerce:manage',

  // Notificaciones
  NOTIFICATION_SEND: 'notification:send'
};

const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS),

  [ROLES.SUPERVISOR]: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.PRODUCT_DELETE,
    PERMISSIONS.CATEGORY_CREATE,
    PERMISSIONS.CATEGORY_READ,
    PERMISSIONS.CATEGORY_UPDATE,
    PERMISSIONS.CATEGORY_DELETE,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.INVENTORY_TRANSFER,
    PERMISSIONS.PURCHASE_CREATE,
    PERMISSIONS.PURCHASE_READ,
    PERMISSIONS.PURCHASE_CANCEL,
    PERMISSIONS.SALE_READ,
    PERMISSIONS.SALE_CANCEL,
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.INVOICE_UPDATE,
    PERMISSIONS.INVOICE_SEND,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.CLIENT_READ,
    PERMISSIONS.CLIENT_UPDATE,
    PERMISSIONS.CONFIG_READ,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.ECOMMERCE_MANAGE,
    PERMISSIONS.NOTIFICATION_SEND
  ],

  [ROLES.CASHIER]: [
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.CATEGORY_READ,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.SALE_CREATE,
    PERMISSIONS.SALE_READ,
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.CLIENT_CREATE,
    PERMISSIONS.CLIENT_READ,
    PERMISSIONS.REPORT_READ
  ],

  [ROLES.INVENTORY]: [
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.CATEGORY_READ,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.INVENTORY_TRANSFER,
    PERMISSIONS.PURCHASE_CREATE,
    PERMISSIONS.PURCHASE_READ,
    PERMISSIONS.REPORT_READ
  ],

  [ROLES.CLIENT]: [
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.CATEGORY_READ,
    PERMISSIONS.SALE_READ,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.CLIENT_READ,
    PERMISSIONS.CLIENT_UPDATE
  ]
};

module.exports = { ROLES, PERMISSIONS, ROLE_PERMISSIONS };
