// ============================================================
// Shared Kernel — Main entry point
// ============================================================

import { createClient } from '@supabase/supabase-js';
import { AsyncLocalStorage } from 'async_hooks';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export * from './domain/index.js';

// ============================================================
// Multi-Tenant Support
// ============================================================

const DEFAULT_COMPANY_ID = '00000000-0000-0000-0000-000000000001';
const __dirname = path.dirname(fileURLToPath(import.meta.url));

/** Global tables without company_id — accessed without tenant filter */
const EXEMPT_TABLES = new Set([
  'companies', 'roles', 'permissions', 'user_roles',
  'system_configurations', 'audit_logs',
]);

/**
 * Tables that HAVE company_id (registry generated by
 * scripts/test-database/schema-contract.mjs). Only these get the
 * automatic company_id injection — tables without the column must
 * NOT be filtered (would cause 42703 errors).
 */
let TENANT_TABLES = new Set();
let TENANT_REGISTRY_LOADED = false;
try {
  const raw = fs.readFileSync(path.join(__dirname, 'tenant-tables.json'), 'utf-8');
  const parsed = JSON.parse(raw);
  TENANT_TABLES = new Set(parsed.tables || []);
  TENANT_REGISTRY_LOADED = true;
} catch {
  console.warn('[shared-kernel] ⚠️ tenant-tables.json no encontrado — proxy SIN filtrado company_id (fail-safe, igual que antes)');
}

/**
 * AsyncLocalStorage instance for request-scoped tenant context.
 * Each request gets its own tenant-aware Supabase client.
 */
export const tenantStorage = new AsyncLocalStorage();

/**
 * Create a tenant-aware Supabase client proxy that auto-injects `company_id`.
 *
 * @param {import('@supabase/supabase-js').SupabaseClient} baseClient - The base Supabase client
 * @param {string} companyId - The company ID to filter by
 * @returns {import('@supabase/supabase-js').SupabaseClient} Proxy-wrapped client
 */
export function createTenantClient(baseClient, companyId) {
  const cid = companyId || DEFAULT_COMPANY_ID;

  return new Proxy(baseClient, {
    get(target, prop, receiver) {
      if (typeof prop === 'symbol') return Reflect.get(target, prop, receiver);

      // Pass through non-table access (auth, storage, rest)
      if (prop === 'auth' || prop === 'storage' || prop === 'rest') {
        return Reflect.get(target, prop, receiver);
      }

      // rpc() passes through (RLS handles filtering for RPCs)
      if (prop === 'rpc') {
        return target.rpc.bind(target);
      }

      // Intercept .from(table) to wrap the query builder
      if (prop === 'from') {
        return function tenantFrom(table) {
          const builder = target.from(table);
          // Tables without company_id (global or not yet migrated) are NOT filtered
          if (EXEMPT_TABLES.has(table) || !TENANT_TABLES.has(table)) return builder;
          return _wrapBuilder(builder, cid);
        };
      }

      // Everything else on the client itself
      const value = Reflect.get(target, prop, receiver);
      return typeof value === 'function' ? value.bind(target) : value;
    },
  });
}

/**
 * Wraps a Supabase query builder with company_id injection.
 */
function _wrapBuilder(builder, companyId) {
  return new Proxy(builder, {
    get(target, prop, receiver) {
      // BUG FIX (2026-08-09): `prop` es el NOMBRE de la propiedad (string),
      // no el valor. El check correcto es `typeof target[prop]`.
      // El bug previo (`typeof prop !== 'function'`, siempre true) hacía que
      // el Proxy NUNCA envolviera el builder → company_id NUNCA se inyectaba.
      if (typeof prop === 'symbol' || typeof target[prop] !== 'function') {
        return Reflect.get(target, prop, receiver);
      }

      return function (...args) {
        // ── SELECT: inject company_id filter ──
        if (prop === 'select') {
          const result = target.select(...args);
          const filtered = result.eq('company_id', companyId);
          return _wrapBuilder(filtered, companyId);
        }

        // ── INSERT / UPSERT: inject company_id into data ──
        if (prop === 'insert' || prop === 'upsert') {
          const [data, options] = args;
          if (data && typeof data === 'object') {
            const injectCompanyId = (item) => ({ company_id: companyId, ...item });
            args[0] = Array.isArray(data) ? data.map(injectCompanyId) : injectCompanyId(data);
          }
          const result = target[prop](...args);
          return _wrapBuilder(result, companyId);
        }

        // ── UPDATE: ensure company_id filter is applied after update() ──
        // (eq() solo existe en PostgrestFilterBuilder, NO en PostgrestQueryBuilder)
        if (prop === 'update') {
          const result = target.update(...args).eq('company_id', companyId);
          return _wrapBuilder(result, companyId);
        }

        // ── DELETE: ensure company_id filter is applied after delete() ──
        if (prop === 'delete') {
          const result = target.delete().eq('company_id', companyId);
          return _wrapBuilder(result, companyId);
        }

        // ── Everything else: pass through ──
        const result = target[prop](...args);

        // If result is a thenable query builder, wrap it
        if (
          result && typeof result === 'object' &&
          typeof result.then === 'function' &&
          typeof result.eq === 'function'
        ) {
          return _wrapBuilder(result, companyId);
        }

        return result;
      };
    },
  });
}

/**
 * Express middleware that creates a tenant-scoped Supabase client
 * and stores it in AsyncLocalStorage for the duration of the request.
 *
 * Reads companyId from req.user.companyId (set by auth middleware)
 * or req.companyId (set by tenantContext in CJS legacy services).
 */
let _baseClient = null;
function _getBaseClient() {
  if (!_baseClient) _baseClient = createSupabaseClient();
  return _baseClient;
}

export function tenantContext(req, res, next) {
  const companyId = req.user?.companyId || req.companyId || req.headers['x-company-id'] || DEFAULT_COMPANY_ID;
  // Exponer companyId en req para los controllers que lo usan explícitamente
  req.companyId = companyId;
  const tenantClient = createTenantClient(_getBaseClient(), companyId);
  tenantStorage.run({ supabase: tenantClient, companyId }, () => next());
}

/**
 * Devuelve el contexto de tenant actual (AsyncLocalStorage).
 * Fuera de una request devuelve `{}` (sin companyId, sin client filtrado).
 */
export function getTenantContext() {
  return tenantStorage.getStore() || {};
}

/**
 * Crea un client Supabase que delega dinámicamente:
 * - Dentro de una request → al client tenant-aware (inyecta company_id)
 * - Fuera de una request (subscribers, workers, health) → al client base
 *
 * Uso: const db = createRequestScopedSupabase(createSupabaseClient());
 *      Los repos reciben `db` y quedan protegidos por tenant automáticamente.
 */
export function createRequestScopedSupabase(baseClient) {
  return new Proxy(baseClient, {
    get(target, prop, receiver) {
      const store = tenantStorage.getStore();
      const active = store?.supabase;
      const src = active || target;
      const value = Reflect.get(src, prop, receiver);
      return typeof value === 'function' ? value.bind(src) : value;
    },
  });
}

// ============================================================
// Supabase Client Factory
// ============================================================

/**
 * Create a configured Supabase client using environment variables.
 * Reads SUPABASE_URL and SUPABASE_SERVICE_KEY from process.env.
 * @returns {import('@supabase/supabase-js').SupabaseClient}
 */
export function createSupabaseClient() {
  const supabaseUrl = process.env.SUPABASE_URL || '';
  const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SERVICE_KEY || process.env.SUPABASE_ANON_KEY || '';

  if (!supabaseUrl) {
    throw new Error('SUPABASE_URL environment variable is required');
  }

  return createClient(supabaseUrl, supabaseServiceKey);
}
